spring:
  application:
    name: service-user
  
  profiles:
    active: local

  flyway:
    locations: classpath:database/migration

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: ${app.swagger.gateway-prefix}/v3/api-docs/swagger-config
    url: ${app.swagger.gateway-prefix}/v3/api-docs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

inapp:
  s3-base-url: ${INAPP_S3_BASE_URL:}

github:
  token: ${GITHUB_TOKEN:}

app:
  swagger:
    enabled: true
    gateway-prefix: /inapp
