server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000   # 커넥션 타임아웃 (20초)
      maximum-pool-size: 10       # 최대 커넥션 풀 크기 (10개)
      minimum-idle: 2             # 최소 유휴 커넥션 수 (2개)
      idle-timeout: 30000         # 유휴 커넥션 타임아웃 (30초)
      pool-name: MyHikariCP
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: false
      format_sql: true
  data:
    redis.repositories.enabled: false
redis:
  master:
    host: ${REDIS_MASTER_HOST}
    port: ${REDIS_PORT}
  slaves:
    - host: ${REDIS_SLAVE_1_HOST}
      port: ${REDIS_PORT}
    - host: ${REDIS_SLAVE_2_HOST}
      port: ${REDIS_PORT}

logging.level:
  org.springframework.boot.autoconfigure: ERROR

app:
  token:
    generate: ${TOKEN_GENERATE_URL}
    verify: ${TOKEN_VERIFY_URL}
    refresh: ${TOKEN_REFRESH_URL}
  jwt:
    issuer: ${JWT_ISSUER}
    tokenServer: ${TOKEN_SERVER_URL}
  youtube:
    key:
      apiKey: ${YOUTUBE_KEY}
    url:
      video: ${YOUTUBE_VIDEO_URL}
      search: ${YOUTUBE_SEARCH_URL}
  gabia:
    id: ${GABIA_ID}
    apiKey: ${GABIA_API_KEY}
    refKey: ${GABIA_REF_KEY}
  neis:
    apiKey: ${NEIS_KEY}
    url: ${NEIS_URL}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
    s3:
      endpoint: ${S3_ENDPOINT}
      bucket: ${S3_BUCKET}

logging:
  level:
    com:
      amazonaws:
        util:
          com.amazonaws.util.EC2MetadataUtils: error