spring:
  application:
    name: service-notice

  profiles:
    active: local

  main:
    web-application-type: servlet

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: ${app.swagger.gateway-prefix}/v3/api-docs/swagger-config
    url: ${app.swagger.gateway-prefix}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  swagger:
    enabled: true
    gateway-prefix: /notice
