package com.b1nd.dodamdodam.inapp.domain.app.exception

import com.b1nd.dodamdodam.core.common.exception.BasicException

class AppAlreadyExistException: BasicException(AppExceptionCode.APP_ALREADY_EXIST)

class AppNotFoundException: BasicException(AppExceptionCode.APP_NOT_FOUND)

class AppReleaseNotFoundException: BasicException(AppExceptionCode.APP_RELEASE_NOT_FOUND)

class AppReleaseEnableNotAllowedException: BasicException(AppExceptionCode.APP_RELEASE_ENABLE_NOT_ALLOWED)

class AppServerAlreadyExistException: BasicException(AppExceptionCode.APP_SERVER_ALREADY_EXIST)

class AppServerNotFoundException: BasicException(AppExceptionCode.APP_SERVER_NOT_FOUND)

class AppServerEnableNotAllowedException: BasicException(AppExceptionCode.APP_SERVER_ENABLE_NOT_ALLOWED)

class AppServerPrefixLevelInvalidException: BasicException(AppExceptionCode.APP_SERVER_PREFIX_LEVEL_INVALID)

class AppServerRedirectPathInvalidException: BasicException(AppExceptionCode.APP_SERVER_REDIRECT_PATH_INVALID)

class AppDenyReasonRequiredException: BasicException(AppExceptionCode.APP_DENY_REASON_REQUIRED)

class AppTeamMemberPermissionRequiredException: BasicException(AppExceptionCode.APP_TEAM_MEMBER_PERMISSION_REQUIRED)

class AppTeamOwnerPermissionRequiredException: BasicException(AppExceptionCode.APP_TEAM_OWNER_PERMISSION_REQUIRED)
