package com.b1nd.dodamdodam.wakeupsong.domain.wakeupsong.exception

import com.b1nd.dodamdodam.core.common.exception.BasicException

class WakeupSongNotFoundException : BasicException(WakeupSongExceptionCode.WAKEUP_SONG_NOT_FOUND)
class WakeupSongNotOwnerException : BasicException(WakeupSongExceptionCode.WAKEUP_SONG_NOT_OWNER)
class YouTubeVideoNotFoundException : BasicException(WakeupSongExceptionCode.YOUTUBE_VIDEO_NOT_FOUND)
class MelonChartFetchFailedException : BasicException(WakeupSongExceptionCode.MELON_CHART_FETCH_FAILED)
class AudioDownloadFailedException : BasicException(WakeupSongExceptionCode.AUDIO_DOWNLOAD_FAILED)
